# Generated by Django 3.1a1 on 2020-05-25 09:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200519_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=8, unique=True, validators=[users.models.validate_student_number], verbose_name='student number'),
        ),
    ]
