version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  groups:
    python-packages:
      patterns:
        - "*"
- package-ecosystem: cargo
  directory: "/resources/exam-proxy"
  schedule:
    interval: monthly
  groups:
    rust-packages:
      patterns:
        - "*"
