version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: cargo
  directory: "/resources/exam-proxy"
  schedule:
    interval: monthly