[tool.poetry]
name = "ctfexam"
version = "0.1.0"
description = "CTF environment which records how people did and lets them upload writeups"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.2"
django-bootstrap4 = "^3.0.0"
docker = "^5.0.0"
bleach = "^3.1.5"
Markdown = "^3.2.2"
pygments = "^2.6.1"
sentry-sdk = "^0.19.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
django-template-check = {git = "https://github.com/thomwiggers/django-template-check.git", rev = "update-tests"}

[tool.black]
exclude = '(/(\.eggs|\.git|\.tox)/|migrations)'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

