# Generated by Django 3.0.6 on 2020-05-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeprocess',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
