# Generated by Django 3.0.6 on 2020-05-14 13:59

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengeprocess_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeentry',
            name='flag',
            field=models.CharField(default=challenges.models.random_flag, max_length=64),
        ),
        migrations.AlterField(
            model_name='challengeentry',
            name='writeup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
