# Generated by Django 3.0.6 on 2020-05-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20200519_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('port', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='challengeprocess',
            name='port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='challenges.Port'),
        ),
    ]
