# Generated by Django 3.0.6 on 2020-05-19 13:18

from django.db import migrations


def _forwards(apps, _schema_editor):
    Port = apps.get_model('challenges', 'Port')
    for port in range(2000, 65535):
        Port.objects.create(port=port)


def _backwards(apps, schema_editor):
    Port = apps.get_model('challenges', 'Port')
    Port.objects.all().delete()


class Migration(migrations.Migration):
    """Add all the ports"""

    dependencies = [
        ('challenges', '0005_auto_20200519_1517'),
        ('challenges', '0009_auto_20200526_1010'),
    ]

    operations = [
        migrations.RunPython(_forwards, _backwards),
    ]
