# Generated by Django 3.0.6 on 2020-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20200519_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='container',
            field=models.CharField(default='echo', max_length=255),
            preserve_default=False,
        ),
    ]
