# Generated by Django 3.1a1 on 2020-05-19 13:56

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challenge_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeentry',
            name='flag',
        ),
        migrations.AddField(
            model_name='challengeentry',
            name='settings',
            field=models.JSONField(default=challenges.models.random_settings),
        ),
    ]
