# Generated by Django 3.1a1 on 2020-06-08 10:22

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challengeprocess_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 22, 56, 493314, tzinfo=utc), verbose_name='no longer available after'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='available from this time'),
        ),
    ]
