# Generated by Django 3.1.4 on 2020-12-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20200608_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeprocess',
            name='port',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
    ]
