# Generated by Django 3.1a1 on 2020-05-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20200519_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
