# Generated by Django 3.1.4 on 2020-12-03 09:58

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challenge_listen_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='listen_ports',
            field=models.JSONField(default=challenges.models.ports_default, help_text="Port, description and if it's logged", verbose_name='Ports exposed by this container'),
        ),
    ]
