# Generated by Django 3.1.4 on 2020-12-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20201203_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='privileged',
            field=models.BooleanField(default=False, help_text='containers that disable ASLR need this.', verbose_name='Needs privileged container'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='container',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='challengeprocess',
            name='process_identifier',
            field=models.TextField(),
        ),
    ]
