---
on: [push,pull_request]

name: Build Rust project

defaults:
  run:
    working-directory: resources/exam-proxy

jobs:
  build_and_test:
    name: Build exam-proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
