---
on: [push]

name: Build Rust project

jobs:
  build_and_test:
    name: Build exam-proxy
    runs-on: ubuntu-latest
    working-directory: resources/exam-proxy
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
