---
on: [push,pull_request]

name: Build Rust project

defaults:
  run:
    working-directory: resources/exam-proxy

jobs:
  build_and_test:
    name: Build exam-proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
